- platform: statistics
  name: "Bedroom brightness over 60 minutes"
  entity_id: sensor.bedroom_brightness_illuminance_lux
  state_characteristic: median
  max_age:
    minutes: 60
  sampling_size: 500
  precision: 0

- platform: statistics
  name: "Kitchen brightness over 60 minutes"
  entity_id: sensor.kitchen_brightness_illuminance_lux
  state_characteristic: median
  max_age:
    minutes: 60
  sampling_size: 500
  precision: 0

- platform: statistics
  name: "Office brightness over 60 minutes"
  entity_id: sensor.office_brightness_illuminance_lux
  state_characteristic: median
  max_age:
    minutes: 60
  sampling_size: 500
  precision: 0

- platform: statistics
  name: "LivingRoom brightness over 60 minutes"
  entity_id: sensor.livingroom_brightness_illuminance_lux
  state_characteristic: median
  max_age:
    minutes: 60
  sampling_size: 500
  precision: 0

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"

- platform: history_stats
  name: Time worked today
  entity_id: switch.office_desk_setup
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) - timedelta(hours=1) }}"
  end: "{{ now().replace(hour=23, minute=59, second=59, microsecond=0) - timedelta(hours=1) }}"

- platform: integration
  source: sensor.photovoltaics_power_used
  name: photovoltaics_energy_used
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.electricity_power
  name: electricity_grid_energy
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.electricity_grid_power_raw
  name: electricity_grid_energy_raw
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.electricity_raw_power_used
  name: electricity_raw_energy_used
  unit_prefix: k
  round: 2
  method: left

- platform: integration
  source: sensor.electricity_grid_power_export
  name: photovoltaics_energy_exported
  unit_prefix: k
  round: 2
  method: left

- platform: history_stats
  name: this_month_power_usage_covered_by_pv
  entity_id: binary_sensor.electricity_power_covered_by_pv
  state: "on"
  type: time
  start: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0 ) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: last_month_power_usage_covered_by_pv
  entity_id: binary_sensor.electricity_power_covered_by_pv
  state: "on"
  type: time
  start: "{{ now().replace(day=1, month=now().month-1, hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now().replace(day=1, hour=0, minute=0, second=0, microsecond=0) }}"

- platform: dwd_weather_warnings
  region_name: !secret dwd_weather_warnings_region_name
