sleep_settings:
  alias: Sleep Settings
  sequence:
    - service: light.turn_off
      entity_id: all
    - service: cover.set_cover_position
      data_template:
        position: "{{ states('input_number.bedtime_cover_position') | int }}"
      enabled: true
      entity_id: all
    - service: media_player.media_stop
      data: {}
      target:
        entity_id:
          - media_player.kitchen
          - media_player.living_room
          - media_player.bedroom
    - service: media_player.unjoin
      data: {}
      target:
        entity_id: media_player.bedroom
    - service: media_player.volume_set
      data:
        volume_level: 0.13
      target:
        entity_id: media_player.bedroom
    - service: media_player.shuffle_set
      data:
        shuffle: true
      target:
        entity_id: media_player.bedroom
    - service: media_player.select_source
      data_template:
        source: "{{ states('input_text.bedtime_sonos_source') }}"
      target:
        entity_id: media_player.bedroom
      enabled: true
    - service: sonos.set_sleep_timer
      data:
        sleep_time: 1800
      target:
        entity_id: media_player.bedroom
    - service: media_player.repeat_set
      data:
        repeat: all
      target:
        entity_id: media_player.bedroom
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.night_mode
  mode: single
  icon: mdi:weather-sunset-down
